import './globals.css'
import { Inter, Space_Grotesk } from 'next/font/google'

import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })
const spaceGrotesk = Space_Grotesk({subsets: ['latin']})

export const metadata = {
  title: 'Joshua Moses - Frontend Engineer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Header/> */}
      <body className={spaceGrotesk.className + " mt-6"}>
        <Header/>
        <div>
        {children}
        </div>
        
        </body>
    </html>
  )
}
