import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import HamburgerMenu from "@/components/HamburgerMenu";
import { PortfolioGlobalProvider } from "@/context/PortfolioGlobalContext";

const inter = Inter({ subsets: ["latin"] });
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Joshua Moses | J0shcodes",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PortfolioGlobalProvider>
        <body
          className={`${inter.className} ${spaceMono.variable} bg-gradient-to-br from-[#0F0F0F] via-[#1A1A1A] to-[#0F0F0F] `}
        >
          <div className="fixed inset-0 overflow-hidden">
            <div className="absolute -top-40 -right-40 w-80 h-80 bg-[#339DFF]/10 rounded-full blur-3xl animate-pulse"></div>
            <div className="absolute top-1/2 -left-40 w-60 h-60 bg-[#339DFF]/5 rounded-full blur-2xl animate-pulse delay-1000"></div>
            <div className="absolute bottom-20 right-1/3 w-40 h-40 bg-[#339DFF]/8 rounded-full blur-2xl animate-pulse delay-2000"></div>
          </div>
          <Header />
          <div>
            <HamburgerMenu />
            {children}
          </div>
          <Footer />
        </body>
      </PortfolioGlobalProvider>
    </html>
  );
}
