// 'use client'

import { useState } from "react";
import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import HamburgerMenu from "@/components/HamburgerMenu";
import { PortfolioGlobalProvider } from "@/context/PortfolioGlobalContext";

const inter = Inter({ subsets: ["latin"] });
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Joshua Moses | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [openHamburgerMenu, setOpenHamburgerMenu] = useState<boolean>(false)
  return (
    <html lang="en">
      <PortfolioGlobalProvider>
        <body className={`${inter.className} ${spaceMono.variable}`}>
          <Header
          // setOpenHamburgerMenu={setOpenHamburgerMenu}
          // openHamburgerMenu={openHamburgerMenu}
          />
          <div>
            <HamburgerMenu />
            {children}
          </div>
          {/* <HamburgerMenu
            // setOpenHamburgerMenu={setOpenHamburgerMenu}
            // openHamburgerMenu={openHamburgerMenu}
          /> */}
          {/* <Footer /> */}
        </body>
      </PortfolioGlobalProvider>
    </html>
  );
}
