import Image from "next/image";

const TechStack = () => {
  return (
    <div className="py-[6.1875rem] px-[7.5625rem] text-[#e6e6e6]">
      <div className="text-center">
        <h2 className="text-4xl font-bold">My Tech Stack/Tools</h2>
        <p className="text-lg mt-4">Technologies and tools I work with</p>
      </div>
      <div className="grid grid-cols-6 mt-14">
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        <div>
          <Image
            className="col-span-1"
            src="/assets/icons/html.svg"
            alt=""
            width={80}
            height={80}
          />
        </div>
        
       
        {/* <Image
          className="col-span-1"
          src="/assets/icons/html.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/css3.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/js.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/typescript.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/python.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/solidity.svg"
          alt=""
          width={50}
          height={50}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/react.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/nextjs2.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/tailwind.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/git.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/githubtechdark.svg"
          alt=""
          width={80}
          height={80}
        />
        <Image
          className="col-span-1"
          src="/assets/icons/vscode.svg"
          alt=""
          width={80}
          height={80}
        /> */}
      </div>
    </div>
  );
};

export default TechStack;
